version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: routeiq
      POSTGRES_PASSWORD: routeiq
      POSTGRES_DB: routeiq
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - "8081:8080"

  api:
    build: ./backend/api
    environment:
      PORT: 8080
      DATABASE_URL: postgres://routeiq:routeiq@db:5432/routeiq?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"

  web:
    build: ./frontend/web
    environment:
      NEXT_PUBLIC_MAPBOX_TOKEN: ""
      WS_URL: ws://localhost:8080/ws
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/web:/app

volumes:
  db_data:
