name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build API
        working-directory: backend/api
        run: |
          go mod tidy
          go build -v ./...

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/web/package.json

      - name: Install and build web
        working-directory: frontend/web
        run: |
          npm ci || npm install
          npm run build
